const CalendarTypes = [
	{
		text: 'Active Task',
		value: 'TA',
		color: '#198754',
		css: 'cal-task-active',
		isBase: false,
	},
	{
		text: 'Projected Task',
		value: 'TP',
		color: '#6c757d',
		css: 'cal-task-pending',
		isBase: false,
	},
	{
		text: 'Task',
		value: 'TN',
		color: '#198754',
		css: 'cal-task',
		isBase: false,
	},
	{
		text: 'Personal Appointment',
		value: 'A',
		color: '#077990',
		css: 'cal-appointment',
		isBase: true,
	},
	{
		text: 'Meeting',
		value: 'M',
		color: '#08A2C0',
		css: 'call-meeting',
		isBase: true,
	},
	{
		text: 'Call',
		value: 'C',
		color: '#055160',
		css: 'cal-call',
		isBase: true,
	},
	{
		text: 'To Do',
		value: 'TD',
		color: '#664d03',
		css: 'cal-to-do',
		isBase: true,
	},
	{
		text: 'Holiday',
		value: 'H',
		color: '#ca6510',
		css: 'cal-holiday',
		isBase: true,
	},
	{
		text: 'Event',
		value: 'E',
		color: '#801F4F',
		css: 'cal-event',
		isBase: false,
	},
	{
		text: 'Event Task',
		value: 'ET',
		color: '#AB286A',
		css: 'cal-event-task',
		isBase: false,
	},
	{
		text: 'Email',
		value: 'EL',
		color: '#CC9A07',
		css: 'cal-email',
		isBase: true,
	},
	{
		text: 'Assignment',
		value: 'AS',
		color: '#59359A',
		css: 'cal-assignment',
		isBase: false,
	},
	{
		text: 'Office Assignment',
		value: 'ASO',
		color: '#432874',
		css: 'cal-office-assignment',
		isBase: false,
	},
]
export default CalendarTypes